export const LOGIN_PENDING = "LOGIN_PENDING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_REJECTED = "LOGIN_REJECTED";

export const REGISTER_PENDING = "REGISTER_PENDING";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_REJECTED = "REGISTER_REJECTED";

export const FORGET_PASSWORD_PENDING = "FORGET_PASSWORD_PENDING";
export const FORGET_PASSWORD_SUCCESS = "FORGET_PASSWORD_SUCCESS";
export const FORGET_PASSWORD_REJECTED = "FORGET_PASSWORD_REJECTED";

export const RESET_AUTH_STATE = "RESET_AUTH_STATE";
